### PR TITLE
"Security"

### LINKED ISSUE #1: Files can be interacted with outside of folder where index.js is stored.
**Issue**  
Outside of where the index.js file is stored, files can be interacted with.  

**Fix**  
Use a host such as Repl.IT or Bluehost to prevent file access outside of the storage space.

### PR DESCRIPTION
**Pull request by torralbaa**
Hi, I made some small changes:
 + Restricted file scope.
 + Merged `'` and `"` into `"` for consistency.

Closes #1 if merged.

### CODE REVIEW

**Comment by ghost** [comment]
Thank you very much, I appreciate your contribution.
I would like to note though, I don't use the return statement. Everything works perfectly fine otherwise.

**Comment by torralbaa** [comment]
> Thank you very much, I appreciate your contribution.

No problem at all, this repo is a really good example of a minimal yet educational script.

> I would like to note though, I don't use the return statement.

Hmm... May I ask why? That `return` statement is there to stop the execution if the file name collides with the script's name.

**Comment by ghost** [comment]
> > I would like to note though, I don't use the return statement.
> 
> Hmm... May I ask why? That `return` statement is there to stop the execution if the file name collides with the script's name.

Well, for most little APIs I use, I usually don't use the return statement, as I have no more code to run after that. I suppose in your case that's helpful though.

**Comment by torralbaa** [comment]
Ah, ok, makes sense.

**Pull request merged**
